version: "3"

services: 
  db:
    environment: 
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_PASSOWRD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:14-alpine'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata:
